#!/bin/sh
WORKDIR=$(dirname $0)
$WORKDIR/update_flag_key || exit 1
cd $WORKDIR || exit 1
if [ -e flagKey ]
then
  flagKey=$(cat flagKey)
  python argo_collector.py -c $WORKDIR/argo.json \
        --input http_no_scipy \
        --output file \
        --callback "http://localhost:8080/erddap/setDatasetFlag.txt?datasetID=argoFloats&flagKey=$flagKey"
else
  python argo_collector.py -c $WORKDIR/argo.json \
         --input http_no_scipy --output file
fi
